# Generated by Django 3.2.7 on 2022-01-20 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='qaDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qareple',
            name='repleDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
