# Generated by Django 3.2.7 on 2022-01-26 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220120_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='qa_user',
            field=models.ForeignKey(db_column='qa_user', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
