# Generated by Django 3.2.7 on 2022-08-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_qa_qa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
