version: '3'
services:
        nginx:
                container_name: nginx
                build: ./nginx
                image: docker/nginx
                #restart: always
                ports:
                        - "80:80"
                network_mode: "host"
                depends_on:
                        - gunicorn


        gunicorn:
                container_name: gunicorn
                build: ./cos_project3
                image: chljidn/recos:${TAG:-recos}
                restart: always
                working_dir: /srv/docker
                command: >
                        bash -c "python manage.py makemigrations
                        && python manage.py migrate
                        && gunicorn --bind 0.0.0.0:8000 cos.wsgi:application --daemon"
                network_mode: "host"
              
