# Generated by Django 3.2.7 on 2022-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('prdname', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='imageupload')),
            ],
        ),
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=10000)),
            ],
        ),
    ]
