# Generated by Django 3.2.7 on 2022-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cos_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cos',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
