# Generated by Django 3.2.7 on 2022-01-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_cos_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewName', models.CharField(max_length=500)),
                ('reviewImage', models.ImageField(blank=True, upload_to='reviewImages')),
                ('reviewContent', models.TextField(blank=True)),
                ('reviewCos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cos')),
                ('reviewUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
