# Generated by Django 3.2.7 on 2022-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cosreviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='letter',
        ),
        migrations.AlterField(
            model_name='cos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
