# Generated by Django 3.2.7 on 2022-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recommend_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_excel',
            name='recommend_file_dir',
            field=models.CharField(max_length=500),
        ),
    ]
