# Generated by Django 3.2.7 on 2022-07-29 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_recommend_excel_recommend_file_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_excel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
