# Generated by Django 3.2.7 on 2022-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recommend_excel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_excel',
            name='file_title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
