# Generated by Django 3.2.7 on 2022-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_recommend_excel_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_excel',
            name='file_title',
            field=models.CharField(max_length=250),
        ),
    ]
